FROM node AS builder
RUN npm i -g @dojo/cli

COPY . /usr/local/app
WORKDIR /usr/local/app

RUN npm i
RUN dojo build

FROM nginx:1.17
COPY --from=builder /usr/local/app/output/dist/ /usr/share/nginx/html/